name: Publish Docker images
on:
  release:
    types: [published]
jobs:  
  jdk-sbt-scala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        name: docker hub
        with:
          path: ./jdk-sbt-scala
          build_args: SBT_VERSION=1.3.9,SCALA_VERSION=2.13.1
          tag_with_ref: true
          username: somdoron
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}          
          repository: unitfinance/jdk-sbt-scala
